### ISSUE TITLE
Train

### ISSUE THREAD

**Issue by Ramesh-X** [yoavartzi/amr#1]
How to create a new model using new dataset..?

**Comment by yoavartzi** [comment]
You will have to prepare the data. You can do it by customizing the customizing this part:
https://github.com/yoavartzi/amr#preparing-the-data-required-only-for-training-and-testing

Then you will need to create .exp files. You can see how they look by looking here:
https://github.com/yoavartzi/amr/blob/master/experiments/dev.proxy/dev.proxy.exp
This includes customizing some of the included files. When you run using such an .exp file, a complete training process starts:
`java -jar dist/amr-1.0.jar experiments/dev.proxy/dev.proxy.exp`

You can also use the included distributed learning framework. The key files for this are:
`experiments/dev.proxy.dev.proxy.dist.exp` (for example)
`experiments/worker/worker.exp`

I am sorry this is not better documented. We hope to improve this in the future, but it will take time.

**Comment by Ramesh-X** [comment]
Thanks for reply. I tried to start the training as you said. I get the following error.

**Reading POS tagger model from /data/ramesh/amr/amr/experiments/dev.proxy/../../resources/stanford-models/english-bidirectional-distsim.tagger ... done [0.5 sec].
Exception in thread "main" java.lang.RuntimeException: org.xml.sax.SAXParseException; systemId: file:///data/ramesh/amr/amr/experiments/dev.proxy/../../resources/propbank/._funnel.xml; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
        at edu.uw.cs.lil.amr.util.propbank.PropBankReader.of(PropBankReader.java:44)
        at edu.uw.cs.lil.amr.util.propbank.PropBank.lambda$new$2(PropBank.java:26)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at edu.uw.cs.lil.amr.util.propbank.PropBank.<init>(PropBank.java:28)
        at edu.uw.cs.lil.amr.lambda.AMRServices.<init>(AMRServices.java:144)
        at edu.uw.cs.lil.amr.lambda.AMRServices.<init>(AMRServices.java:50)
        at edu.uw.cs.lil.amr.lambda.AMRServices$Builder.build(AMRServices.java:710)
        at edu.uw.cs.lil.amr.Init.init(Init.java:129)
        at edu.uw.cs.lil.amr.exp.AmrExp.<init>(AmrExp.java:87)
        at edu.uw.cs.lil.amr.exp.AmrExp.<init>(AmrExp.java:117)
        at edu.uw.cs.lil.amr.exp.AmrGenericExperiment.main(AmrGenericExperiment.java:28)
        at edu.uw.cs.lil.amr.Main.main(Main.java:61)
Caused by: org.xml.sax.SAXParseException; systemId: file:///data/ramesh/amr/amr/experiments/dev.proxy/../../resources/propbank/._funnel.xml; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:994)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:274)
        at edu.uw.cs.lil.amr.util.propbank.PropBankReader.of(PropBankReader.java:42)
        ... 21 more**

`._funnel.xml` file that is reffered in the error is attached here as funnel.txt file. Hope for a help..
[funnel.txt](https://github.com/yoavartzi/amr/files/574394/funnel.txt)

**Comment by yoavartzi** [comment]
Sorry for the delayed reply.

I am not sure why this is happening. This looks like a problem in either
our PropBank reader or in the PropBank files you have. That said, I don’t
think we ended up using PropBank in any meaningful way. I suggest trying to
delete the “propBank=“ line in experiments/params.inc.

If you try it, can you let me know if it works?

Thanks,

Yoav

**Comment by yoavartzi** [comment]
This problem might be due to issue https://github.com/yoavartzi/amr/issues/2

I fixed the getres.sh script, so hopefully this issue is solved now. Closing it.

Thanks
